### ISSUE TITLE
Archive the repo?

### ISSUE THREAD

**Issue by webknjaz** [bitprophet/alabaster#179]
There hasn't been a release since 2018 and the last commit implies that this project isn't going to be maintained anymore. So it'd probably be reasonable to just archive it or at least pin an issue + a readme message stating the status explicitly.

**Comment by jdillard** [comment]
It looks like the maintainer posted a Help Wanted ad in June of 2020: http://bitprophet.org/blog/2020/07/02/help-wanted/

Seems a better alternative to archiving the repo (for now), would be to see if we can find enough help and/or someone qualified to take over the maintainer role.

**Comment by webknjaz** [comment]
I seem to vaguely recall reading that post. It doesn't mention this specific project, though.

**Comment by jdillard** [comment]
Typically burn out effects all projects 😞

**Comment by webknjaz** [comment]
cc @bitprophet :point_up:

**Comment by bitprophet** [comment]
Alabaster's kind of inbetween - yes, burnout, but also it's (slightly) less prone to bitrot than my other projects / is in a more stable place so its priority always lags behind the others :(

I'm intending to see whether I can convince some of the Sphinx contributors to take it over, since it's the default there now. There will be announcements if/when that happens and I assume it'd move into their GH org.

**Comment by jdillard** [comment]
Glad to hear there are conversations with some of the Sphinx contributors, I tried to look but couldn't find any.
