### ISSUE TITLE
Use webfonts for garamond?

### ISSUE THREAD

**Issue by alex** [bitprophet/alabaster#37]
The theme looks _amazing_ with Garamond, which unfortunately isn't installed on OS X by default. It'd be super sweet if there was a webfont for this.

**Comment by bitprophet** [comment]
I'm web-font-challenged (including both literal webfonts and general "doing font things on the web") but if you can identify the right way to add support for this (obviously with fallback) I'd totally go for it.

Also, a screenshot example would be rad, I don't seem to have Garamond on my system.

**Comment by alex** [comment]
This is what it looks like with all the fonts, it looks like there's a few other fonts beyond Garamond that are used (Garamond is just the title one)

![screen shot 2015-06-11 at 3 12 40 pm](https://cloud.githubusercontent.com/assets/772/8115857/69f0e66c-104c-11e5-91aa-604487c1cc5e.png)

I believe all these fonts (or very very similar replacements) are available from Google Fonts, so I think it's just a matter of adding the appropriate tags to `<head>`? https://www.google.com/fonts

Going to go ahead and CC @idan as the relevant knowledgable person :-)

**Comment by welchbj** [comment]
For anyone coming here looking to load a custom font (such as through Google fonts), a quick workaround that has worked for me is to use `@import` your `custom.css` file, and then set your body/head fonts through the customization parameters (in this case, `font_family` and `head_font_family`) provided by alabaster.

**Comment by bitprophet** [comment]
I can't remember exactly when Sphinx 1.3 came out but since then we've been the default which is another strong argument against requiring loading of a webfont.

We could add it as an opt-in setting but I'm not sure we even want to encourage this? Think of folks on slow Internet of various kinds.

Gonna close on this basis (since we're also finally closing out #73 -- but if someone dropped a PR that accomplished this in an opt-in manner I _might_ reconsider `¯\_(ツ)_/¯`
