### ISSUE TITLE
encoding error when openening readme in setup.py

### ISSUE THREAD

**Issue by arunpersaud** [bitprophet/alabaster#40]
Hi

In commit a8c8b2cd3f8546245e36976ed2c12662b0fd4117 should this be:

    with open('README.rst'), encoding='utf-8') as f:
        readme = f.read() 

I'm getting the following error when building using python3 (on the opensuse build server)

     python3 setup.py build
    [   97s] Traceback (most recent call last):
    [   97s]   File "setup.py", line 13, in <module>
    [   97s]     readme = f.read()
    [   97s]   File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    [   97s]     return codecs.ascii_decode(input, self.errors)[0]
    [   97s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15684: ordinal not in range(128)
    [   97s] error: Bad exit status from /var/tmp/rpm-tmp.SU1PL3 (%build)

see https://build.opensuse.org/package/live_build_log/home:apersaud:branches:devel:languages:python3/python3-alabaster/openSUSE_13.2/x86_64

**Comment by kormat** [comment]
Can confirm i'm seeing the same issue on ubuntu trusty.

**Comment by maxtepkeev** [comment]
This happens because of the ``ä`` in ``Tomi Pieviläinen`` surname on line 405, so I would just change it to a simple ``a``.

**Comment by jsbueno** [comment]
Sorry - mutilating people's names is not a solution for Unicode Errors. The proper fix is specifying the encoding to open the file.

**Comment by wiliamsouza** [comment]
I agree with @jsbueno fix this forever!

**Comment by maxtepkeev** [comment]
Well, from my poing of view readme and changelog files shouldn't contain any unicode characters, but if you insist then we can do it this way also, but not with builtin ``open`` because it doesn't have an encoding parameter under Python 2. We need to use codec's module ``open``:

```python
import codecs
with codecs.open('README.rst', 'r', 'utf-8') as f:
    readme = f.read() 
```

**Comment by wiliamsouza** [comment]
LGTM :+1:

**Comment by flacjacket** [comment]
It'd be nice to get this fix in a 0.7.6 release so the current sphinx release (which requires alabaster<0.8) isn't broken. Noticed this when my RTD builds started failing with Python 3, would like to get them working without a new sphinx release, too.

**Comment by bitprophet** [comment]
Ugh, gross, sorry about this. Unsure why it's not complaining on my local dev system - I do my `setup.py` business with Python 2, but I still can't recreate it with `python3 setup.py build`.

In the past on other projects we've simply solved this by slapping an encoding comment at the top of the file, so I will try that once I can find a platform that lets me recreate the issue locally (or on Travis).

**Comment by bitprophet** [comment]
Also, I'm curious to hear the rationale for @maxtepkeev's argument about no unicode in readmes/changelogs - if anything, it feels like we should be transitioning to a world where the default text encoding is Unicode, no?

I am not a Unicode wizard but I do agree with @jsbueno that honoring contributors' names is important, and I always take steps to correct display issues when they are brought to my attention.

**Comment by bitprophet** [comment]
Seems replicating it was as simple as changing my `$LANG` from `en_us.UTF-8` to, well, anything not that.

I checked and my earlier memory was about encoding issues in *actual Python source files*, where the interpreter honors comments like `# -*- coding: utf-8 -*-`. Not gonna work here, so yea, going to use `codecs.open`.

**Comment by maxtepkeev** [comment]
@bitprophet The rationale for this is very simple. Readme, Changelog, License and similar files contain very important information (how to use a library, changes between versions, license information etc) which should be accessible and readable on all platforms despite of the locale being used. When we use unicode characters in this files, people on the platforms without unicode support can't see all information as they should, because unicode characters will be replaced by the unreadable symbols and that fact may lead to people's frustration. I agree that we should move to the world where the default text encoding is Unicode, but we also shouldn't forget about other people who don't have unicode support on their systems.

Now about people's names. I'm Russian but as you see I don't write my name and surname in Russian because I know that if I do that 2 things will happen:

1) Some people will see my name as unreadable symbols
2) All people that aren't from Russia will have no idea how to read my name and surname and which part of my name is actually name and which is the surname (this is most important part imho)

That is why I write my name in English to make everybody happy, I also have a lot of other examples. I know a lot of German people with the surname Müller, but they write it as Muller again to make everybody happy. And there is nothing wrong with that approach because English is an international language which almost all people can read and understand.

Finally you can have a look at other packages and while you will see that some of them use ``codecs.open`` approach, most of them just don't allow unicode in the Readme, Changelog etc files to make all people happy.

I'm not trying to offend somebody or to push or something, this is just MY point of view to this problem.

**Comment by bitprophet** [comment]
@maxtepkeev Thanks for elaborating. I don't fully agree but I see where you're coming from.

Also, the only reason this is an issue in this project is I've been lazy and avoided a "full" Sphinx docs tree. Once I get around to doing that, the changelog will leave README and go elsewhere and it'll be moot :)

**Comment by tpievila** [comment]
Found this when our Docker builds failed... For the record, I'm in the middle of changing my name to ASCII (no, not because of this issue ;), but it will take a few more months, so please don't shoot me if I kinda broke a significant portion of rtd.org builds.
