### ISSUE TITLE
Nested lists in narrow screens become hard to understand

### ISSUE THREAD

**Issue by bgeron** [bitprophet/alabaster#45]
The bullets and text are all flattened to the same horizontal alignment.

# To reproduce

1. Put the following in a Sphinx document:

    * a

      * b

        * c

      * d
        
        * e

    * f
      
      * g
       
    * h

2. Render using the Alabaster theme
3. Make your browser less than 870 browser pixels wide.
4. The bullets will be different, but all bullets and text should be aligned.

**Comment by homeworkprod** [comment]
Stumbled upon this myself, and agree.

Also, I noticed that bullet lists aren't indented on narrow screens, but that's ok for me as it is a style I've seen elsewhere (and makes sense, too).

**Comment by bitprophet** [comment]
Sounds legit, that sub-stylesheet of sorts often gets overlooked since it's not viewed as much. Gonna roll this ticket into the PR. Thanks!

**Comment by homeworkprod** [comment]
Just to make sure that we're on the same page here, I created this image from two screenshots of the rendering in a wide browser window (on the left) and a narrow one (on the right):

![alabaster_lists_wide-vs-narrow_indentation](https://cloud.githubusercontent.com/assets/95277/9400468/d57eaad4-47c1-11e5-962b-fe6e22dbd60e.png)

I assume that @bgeron was referring to the fact that in the narrow window, the nested bullets' levels differ only in the type of bullet, but they are all at the same horizontal position.

What I was additionally referring to is the fact that the whole list itself is more shifted to the left in the narrow window so that the bullets' labels horizontally align with the surrounding text ("Contents:" in this case).
As I was trying to say, this indentation of the whole list is something not uncommon to me (maybe even more readable at times) and well-suited for a narrow screen (depending on the outermost margin/whitespace available). That is something that doesn't have to change, I think.

**Comment by bgeron** [comment]
> I assume that @bgeron was referring to the fact that in the narrow window, the nested bullets' levels differ only in the type of bullet, but they are all at the same horizontal position.

Exactly.

> As I was trying to say, this indentation of the whole list is something not uncommon to me (maybe even more readable at times) and well-suited for a narrow screen (depending on the outermost margin/whitespace available). That is something that doesn't have to change, I think.

I agree, it's a very nice style that way! I think it was on purpose, because there is a rule for exactly that  in the CSS: https://github.com/bgeron/alabaster/blob/master/alabaster/static/alabaster.css_t#L460 (it's in a @media block).

**Comment by bitprophet** [comment]
The "indented such that bullets are left of paragraph text" thing is something the main style used to do as well, and I actually find it distasteful on desktop window sizes. BUT I totally get how it's nice in the narrower window use case, so I am also +1 on preserving that - thanks a lot for the clarifications.
